# Generated by Django 4.2.1 on 2023-05-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.IntegerField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
