# Generated by Django 4.2.1 on 2023-06-01 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optics', '0003_alter_optics_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optics_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('current_price', models.IntegerField()),
                ('is_processed', models.BooleanField()),
                ('is_completed', models.BooleanField()),
                ('optic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='optics.optics')),
            ],
        ),
    ]
