# Generated by Django 4.2.1 on 2023-06-06 10:30

from django.db import migrations, models
import orders_on_optic.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_on_optic', '0002_alter_optics_order_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optics_order',
            name='phone',
            field=models.CharField(max_length=15, validators=[orders_on_optic.models.validate_phone_number]),
        ),
    ]
