# Generated by Django 4.2.1 on 2023-06-05 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('current_price', models.IntegerField()),
                ('time', models.DateField()),
                ('is_processed', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.services')),
            ],
        ),
    ]
