# Generated by Django 4.2.1 on 2023-06-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders_on_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services_order',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
